javascript課題④
vitz1300/moomin pull request #10
Opened 2020-11-01 14:24 UTC by vitz1300

2020-11-02 13:59 UTC, myzktkyk requested changes
課題の示す仕様を満たす動きができていることが確認できました。
ただ、1点指摘をすると…現状選択肢の1番上が常に正解となってしまい
クイズアプリとしては面白みに欠ける状態になっています。
できれば選択肢をシャッフルしてほしいです。

2020-11-02 13:59 UTC, myzktkyk commented on main.js
> +  fetch('https://opentdb.com/api.php?amount=11')
なぜ `amount=11` なのでしょうか？
`amount=10` ではダメな理由を教えていただければと思います。

2020-11-10 05:54 UTC, manaberuit reviewed
シャッフル部分はOKです！
デコード部分に関して一点だけコメントしましたので、そちらだけ修正できるか挑戦してみましょう！

2020-11-10 05:54 UTC, manaberuit commented on main.js
> +const decodeUrl = decodeURI('https://opentdb.com/api.php?amount=10');
こちらのURLに対してdecodeURLを使用しても意味がないですよ^^
関数名のURLが少し分かりづらいかもしれませんが、miyzakiさんがお伝え頂いた以下の記事の例をもう一回確認してみましょう！
https://techacademy.jp/magazine/36973#sec3

エスケープされた文字列をdecodeURLの引数に指定していることが分かるかと思います。
今回エスケープされてしまっている（＝文字化けしているような）文字列は何だった思い出してください。
こちらの「https://opentdb.com/api.php?amount=10」はエスケープされていないはずです。

エスケープされている文字列に対してdecodeURLを使用するようにしてみてください^^

2020-11-18 11:52 UTC, merged